### ISSUE TITLE
Gets tripped up by double letters guesses where one is wrong

### ISSUE THREAD

**Issue by ejleslie** [sadmoody/unwordle-svelte#4]
It appears that the guessing algorithm doesn't know how to handle situations where a double-letter word has been guessed but only one of the double letters is in the correct word, or at least I'm guessing that's the issue.

See example: 

![chrome_AKRYJZW5BO](https://user-images.githubusercontent.com/81496829/153020603-42a225db-daad-4afd-87d1-8303354ac833.png)

SHINE is one of the standard first guesses, and BRASS was on the guest list after filling in the response for SHINE.

The response for BRASS, however, has left it with no remaining guesses, even though many words solve the puzzle under these constraints.

(This was the answer:

![chrome_2sSsN49ED0](https://user-images.githubusercontent.com/81496829/153020857-8b699ebc-73b7-416e-99ae-aa465ae6ec4c.png)
)

No idea whether you're taking bug feedback on the tool but since I ran across it while testing it out on WordleUnlimited (game ID in screenshot if you want to recreate) I figured I'd log it.

**Comment by sadmoody** [comment]
Hey there, thanks for the submission. There isn't a bug here, it's just that the word "traps" isn't on the original Wordle so it's not added as a potential answer. It's a valid entry, but not a valid solution.

**Comment by ejleslie** [comment]
Oh! Okay, fair enough. I figured wordleunlimited and actual wordle shared the same word bank, but knowing that's not the case, that makes sense. Thanks for looking!
